In [1]:
from numpy import random
print(random.randint(1,100))#random integer in given range
print(random.rand())#float number 0-1

55
0.39749776907070367


In [2]:
#create n-dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[ 7 64 28]
[[24 53 82 30]
 [87 74 15 15]
 [80 95 65  6]]
[[[55 89]
  [ 5 23]
  [79 68]
  [98 74]]

 [[94 19]
  [57 42]
  [76 87]
  [69 56]]

 [[68 77]
  [34 45]
  [20 72]
  [31 56]]]


In [3]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.031417619672286956
[0.49731842 0.06093112 0.73216205]
[[0.90856434 0.83865625 0.0686193 ]
 [0.51986494 0.10690027 0.83451524]]


In [7]:
a= random.randint(100,size=(3,4)).ravel()
a

array([42, 76, 10, 24, 65,  0, 71, 69, 70, 38, 71,  6])

In [8]:
random.choice(a)

6

In [9]:
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 1, 5, 5],
       [3, 2, 4, 2],
       [5, 3, 3, 3],
       [2, 3, 2, 3]])

In [10]:
random.choice(a)

38

### Pandas:
1.  Data manipulation,analysis and clening
2.  Tabular,Unlabelled

### Created a Data Frame
1.  Using-
2.  Dictionaries

In [15]:
import pandas as pd
import numpy as np
dict1 ={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 ={'a':5,'b':6,'c':7,'d':8,'e':9}
data ={"First":dict1,"second":dict2}
df=pd.DataFrame(data,dtype=np.float)
df

First  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     9.0

In [16]:
d1 ={"name":["suhas","lohith","bhargav"],"address":["hyd","adb","Ap"]}
df1 =pd.DataFrame(d1)
df1

name address
0    suhas     hyd
1   lohith     adb
2  bhargav      Ap

In [22]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data ={"column1":s1,"column2":s2,"column":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column
0        1    12.23      a
1        2    23.34      b
2        3    45.30      c
3        4    45.50      d
4        5    67.78      e
5        6    34.45      f
6        7    23.34      g
7        8    67.40      h
8        9    23.00      i
9       10      NaN      j

### Selecting the data from the Data Frame:
1.  loc
1.   iloc

In [19]:
df3["coloumn1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: coloumn1, dtype: int64

In [24]:
df3.loc[0:5,["column1","column2","column"]]

column1  column2 column
0        1    12.23      a
1        2    23.34      b
2        3    45.30      c
3        4    45.50      d
4        5    67.78      e
5        6    34.45      f

In [25]:
#using single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [27]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retreving Information of the Data Frame

In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  9 non-null      float64
 2   column   10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


### viewng data frame

In [29]:
df3.head()

column1  column2 column
0        1    12.23      a
1        2    23.34      b
2        3    45.30      c
3        4    45.50      d
4        5    67.78      e

In [30]:
df3.head(3)

column1  column2 column
0        1    12.23      a
1        2    23.34      b
2        3    45.30      c

In [31]:
df3.tail()

column1  column2 column
5        6    34.45      f
6        7    23.34      g
7        8    67.40      h
8        9    23.00      i
9       10      NaN      j

In [32]:
df3.tail(3)

column1  column2 column
7        8     67.4      h
8        9     23.0      i
9       10      NaN      j

In [37]:
df3 = df3.rename(columns={"column1":"First",
                          "column2":"Second",
                          "column":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.78     e
5      6   34.45     f
6      7   23.34     g
7      8   67.40     h
8      9   23.00     i
9     10     NaN     j